### ISSUE TITLE
Pubsub to see running entries

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/cy-time#15]
It should be possible to get a list of entries that are running.

**Comment by JasperStam** [comment]
This changes our the current pubsub architecture. Previously when you subscribed on a scope, you received publishes if models within your scoped were added updated or deleted.

However this changes changes the semantics of subscribing. Instead of receiving publishes of models within your scope, the publishes will specify changes relative to your scope.

With this new version of subscribing, `delete` in the publish will be renamed to `remove`. If you subscribed on entries with scope: `ended_at: null`, and an entry currently in your scope gets updated to `ended_at: bla`, the publish will contain this model under the `remove` key. The model has been removed from your scope even though the action on the model was an `update`.

So the keys of the publish event could mean the following:
- `add`:
  - a new model gets added and fits your scope
  - a model gets updated, before the update it didn't match your scope, after the update it does match your scope
- `update`:
  - a model already in your scope gets updated
- `remove`:
  - a model in your scope gets deleted
  - a model in your scope gets updated and the updated version doesn't match your scope

**Comment by SpaceK33z** [comment]
Toppie
